version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: realburger-mongo
    ports:
      - "27018:27017"
    volumes:
      - realburger_db_data:/data/db
    restart: unless-stopped

volumes:
  realburger_db_data:
